/* tslint:disable */
/* eslint-disable */
/**
 * Tilled API
 * The Tilled API is organized around [REST](http://en.wikipedia.org/wiki/Representational_State_Transfer). Our API has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, and uses standard HTTP response codes, authentication, and verbs.  Tilled’s API has two public environments, `sandbox` and `production`. The former does not affect live data or interact with banking networks. Prior to certification completion, only `sandbox` is available.  Authentication uses a standard web token schema.  **Notice**: Tilled’s API uses HTTP status `401` for `Unauthenticated` (not `Unauthorized`). Requests for unauthorized materials will receive a `403: Forbidden` response. [Learn more about error codes >](https://docs.tilled.com/docs/resources/error-codes)  ## Authentication  Tilled’s API uses API keys for authentication, which can be managed in the Tilled Dashboard. Keys created in the sandbox environment will not work in production nor will production credentials work in the sandbox.  Restricted API keys can provide granular permissions.  Keep your API keys secure and do not share them publicly, such as on GitHub or in client-side code. Authentication is done via the custom HTTP header `tilled-api-key`, with your API key as the value. All requests must be over HTTPS; HTTP requests will fail, as will unauthenticated requests.  ## JWT  Create a JSON Web Token (JWT) using our [Login endpoint](https://docs.tilled.com/api-reference#tag/users/post/v1/auth/login). Use the format: Bearer <JWT>. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: integrations@tilled.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BalanceTransactionFeeDetail
 */
export interface BalanceTransactionFeeDetail {
    /**
     * Amount of the fee, in currency minor units.
     * @type {number}
     * @memberof BalanceTransactionFeeDetail
     */
    'amount': number;
    /**
     * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase.
     * @type {string}
     * @memberof BalanceTransactionFeeDetail
     */
    'currency': BalanceTransactionFeeDetailCurrency;
    /**
     * Type of the fee, one of: `platform_fee`, `tilled_fee` or `tax`.
     * @type {string}
     * @memberof BalanceTransactionFeeDetail
     */
    'type': BalanceTransactionFeeDetailType;
    /**
     * ID of the `partner` account that earned the fee, if any.
     * @type {string}
     * @memberof BalanceTransactionFeeDetail
     */
    'account_id'?: string;
    /**
     * An arbitrary string attached to the object. Often useful for displaying to users.
     * @type {string}
     * @memberof BalanceTransactionFeeDetail
     */
    'description'?: string;
}

export const BalanceTransactionFeeDetailCurrency = {
    AUD: 'aud',
    CAD: 'cad',
    DKK: 'dkk',
    EUR: 'eur',
    HKD: 'hkd',
    JPY: 'jpy',
    NZD: 'nzd',
    NOK: 'nok',
    GBP: 'gbp',
    ZAR: 'zar',
    SEK: 'sek',
    CHF: 'chf',
    USD: 'usd'
} as const;

export type BalanceTransactionFeeDetailCurrency = typeof BalanceTransactionFeeDetailCurrency[keyof typeof BalanceTransactionFeeDetailCurrency];
export const BalanceTransactionFeeDetailType = {
    PLATFORM_FEE: 'platform_fee',
    TILLED_FEE: 'tilled_fee',
    TAX: 'tax',
    CHARGEBACK_FEE: 'chargeback_fee'
} as const;

export type BalanceTransactionFeeDetailType = typeof BalanceTransactionFeeDetailType[keyof typeof BalanceTransactionFeeDetailType];


