/* tslint:disable */
/* eslint-disable */
/**
 * Tilled API
 * The Tilled API is organized around [REST](http://en.wikipedia.org/wiki/Representational_State_Transfer). Our API has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, and uses standard HTTP response codes, authentication, and verbs.  Tilled’s API has two public environments, `sandbox` and `production`. The former does not affect live data or interact with banking networks. Prior to certification completion, only `sandbox` is available.  Authentication uses a standard web token schema.  **Notice**: Tilled’s API uses HTTP status `401` for `Unauthenticated` (not `Unauthorized`). Requests for unauthorized materials will receive a `403: Forbidden` response. [Learn more about error codes >](https://docs.tilled.com/docs/resources/error-codes)  ## Authentication  Tilled’s API uses API keys for authentication, which can be managed in the Tilled Dashboard. Keys created in the sandbox environment will not work in production nor will production credentials work in the sandbox.  Restricted API keys can provide granular permissions.  Keep your API keys secure and do not share them publicly, such as on GitHub or in client-side code. Authentication is done via the custom HTTP header `tilled-api-key`, with your API key as the value. All requests must be over HTTPS; HTTP requests will fail, as will unauthenticated requests.  ## JWT  Create a JSON Web Token (JWT) using our [Login endpoint](https://docs.tilled.com/api-reference#tag/users/post/v1/auth/login). Use the format: Bearer <JWT>. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: integrations@tilled.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PaymentMethodCreateParamsAchDebit } from './payment-method-create-params-ach-debit';
// May contain unused imports in some cases
// @ts-ignore
import { PaymentMethodCreateParamsBillingDetails } from './payment-method-create-params-billing-details';
// May contain unused imports in some cases
// @ts-ignore
import { PaymentMethodCreateParamsCard } from './payment-method-create-params-card';
// May contain unused imports in some cases
// @ts-ignore
import { PaymentMethodCreateParamsEftDebit } from './payment-method-create-params-eft-debit';

/**
 * 
 * @export
 * @interface PaymentMethodCreateParams
 */
export interface PaymentMethodCreateParams {
    /**
     * The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type. If the selected type is `card_present`, then `terminal_reader_id` is required.
     * @type {string}
     * @memberof PaymentMethodCreateParams
     */
    'type': PaymentMethodCreateParamsType;
    /**
     * 
     * @type {PaymentMethodCreateParamsAchDebit}
     * @memberof PaymentMethodCreateParams
     */
    'ach_debit'?: PaymentMethodCreateParamsAchDebit;
    /**
     * 
     * @type {PaymentMethodCreateParamsBillingDetails}
     * @memberof PaymentMethodCreateParams
     */
    'billing_details'?: PaymentMethodCreateParamsBillingDetails;
    /**
     * 
     * @type {PaymentMethodCreateParamsCard}
     * @memberof PaymentMethodCreateParams
     */
    'card'?: PaymentMethodCreateParamsCard;
    /**
     * 
     * @type {PaymentMethodCreateParamsEftDebit}
     * @memberof PaymentMethodCreateParams
     */
    'eft_debit'?: PaymentMethodCreateParamsEftDebit;
    /**
     * Set of [key-value pairs](#section/Metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value (i.e. `\'\'` or `null`) to them. All keys can be unset by posting an empty value (i.e. `{}` or `null`) to `metadata`.
     * @type {{ [key: string]: string; }}
     * @memberof PaymentMethodCreateParams
     */
    'metadata'?: { [key: string]: string; };
    /**
     * A customer provided name for the PaymentMethod.
     * @type {string}
     * @memberof PaymentMethodCreateParams
     */
    'nick_name'?: string;
    /**
     * A token generated by Tilled.js representing the details of a payment method (e.g. card or bank details)
     * @type {string}
     * @memberof PaymentMethodCreateParams
     */
    'payment_token'?: string;
    /**
     * Required if this is a `card_present` PaymentMethod, this is the id of terminal reader you want to use to collect card information. Starts with a prefix `term_`
     * @type {string}
     * @memberof PaymentMethodCreateParams
     */
    'terminal_reader_id'?: string;
}

export const PaymentMethodCreateParamsType = {
    CARD: 'card',
    ACH_DEBIT: 'ach_debit',
    EFT_DEBIT: 'eft_debit',
    CARD_PRESENT: 'card_present'
} as const;

export type PaymentMethodCreateParamsType = typeof PaymentMethodCreateParamsType[keyof typeof PaymentMethodCreateParamsType];


