/* tslint:disable */
/* eslint-disable */
/**
 * Tilled API
 * The Tilled API is organized around [REST](http://en.wikipedia.org/wiki/Representational_State_Transfer). Our API has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, and uses standard HTTP response codes, authentication, and verbs.  Tilled’s API has two public environments, `sandbox` and `production`. The former does not affect live data or interact with banking networks. Prior to certification completion, only `sandbox` is available.  Authentication uses a standard web token schema.  **Notice**: Tilled’s API uses HTTP status `401` for `Unauthenticated` (not `Unauthorized`). Requests for unauthorized materials will receive a `403: Forbidden` response. [Learn more about error codes >](https://docs.tilled.com/docs/resources/error-codes)  ## Authentication  Tilled’s API uses API keys for authentication, which can be managed in the Tilled Dashboard. Keys created in the sandbox environment will not work in production nor will production credentials work in the sandbox.  Restricted API keys can provide granular permissions.  Keep your API keys secure and do not share them publicly, such as on GitHub or in client-side code. Authentication is done via the custom HTTP header `tilled-api-key`, with your API key as the value. All requests must be over HTTPS; HTTP requests will fail, as will unauthenticated requests.  ## JWT  Create a JSON Web Token (JWT) using our [Login endpoint](https://docs.tilled.com/api-reference#tag/users/post/v1/auth/login). Use the format: Bearer <JWT>. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: integrations@tilled.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserInvitationCreateParams
 */
export interface UserInvitationCreateParams {
    /**
     * Email address
     * @type {string}
     * @memberof UserInvitationCreateParams
     */
    'email': string;
    /**
     * The user\'s role, primarily used in the Tilled Dashboard. The roles have varied restrictions on the actions they can take.  `admin` Best for business owners and company administrators.  `developer` Best for developers or people primarily using the Tilled API.  `analyst` Best for people who need full access to Tilled data, but don\'t need to update business settings.  `view_only` Best for people who need to view Tilled data, but don\'t need to make any updates.
     * @type {string}
     * @memberof UserInvitationCreateParams
     */
    'role': UserInvitationCreateParamsRole;
    /**
     * The type of email, if any, that should be sent to the new user. Defaults to `console_invitation` if one is not provided.  `merchant_application` \"You\'ve been invited by {partner name} to complete the setup of your payment processing account. To create your account and access your application follow the link below. {user invitation link}\"  `none` No email sent.  `console_invitation` - For **merchant** accounts: \"You have been invited to join *{{account name}}\'s* payment processing account with *{{partner name}}*.<br><br> *{user invitation hyperlink button}*<br><br> You will gain access to the team\'s Dashboard, including information about payments, payouts, and more. The invitation link will expire in 7 days.\" --- - For **partner** accounts: \"You have been invited to join *{{account name}}\'s* payment processing account with *{{parent name}}*.<br><br> *{user invitation hyperlink button}*<br><br> You will gain access to the team\'s Dashboard, including information about merchants, payments, payouts, and more. The invitation link will expire in 7 days.\" --- - For **reseller** accounts: \"You have been invited to join *{{account name}}\'s* payment processing account.<br><br> *{user invitation hyperlink button}*<br><br> You will gain access to the team\'s Dashboard, including information about your software platforms, merchants, payments, and more. The invitation link will expire in 7 days.\"
     * @type {string}
     * @memberof UserInvitationCreateParams
     */
    'email_template'?: UserInvitationCreateParamsEmailTemplate;
}

export const UserInvitationCreateParamsRole = {
    ADMIN: 'admin',
    DEVELOPER: 'developer',
    ANALYST: 'analyst',
    VIEW_ONLY: 'view_only',
    MERCHANT_OWNER: 'merchant_owner',
    MERCHANT_ADMIN: 'merchant_admin',
    RESELLER_OWNER: 'reseller_owner',
    RESELLER_ADMIN: 'reseller_admin',
    RESELLER_VIEW_ONLY: 'reseller_view_only',
    RESELLER_SALES_REP: 'reseller_sales_rep',
    RESELLER_SUPPORT_SPECIALIST: 'reseller_support_specialist',
    RESELLER_INTEGRATION_ANALYST: 'reseller_integration_analyst'
} as const;

export type UserInvitationCreateParamsRole = typeof UserInvitationCreateParamsRole[keyof typeof UserInvitationCreateParamsRole];
export const UserInvitationCreateParamsEmailTemplate = {
    MERCHANT_APPLICATION: 'merchant_application',
    NONE: 'none',
    CONSOLE_INVITATION: 'console_invitation'
} as const;

export type UserInvitationCreateParamsEmailTemplate = typeof UserInvitationCreateParamsEmailTemplate[keyof typeof UserInvitationCreateParamsEmailTemplate];


